name: core
description: Flutter core module
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  injectable: ^1.5.3
  http_interceptor: ^1.0.2
  http: ^0.13.4
  get_it: ^7.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  transparent_image: ^2.0.0
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator:
  build_runner:

flutter:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/robotocondensed_bold.ttf
          style: normal
          weight: 700
        - asset: fonts/robotocondensed_bolditalic.ttf
          style: italic
          weight: 700
        - asset: fonts/robotocondensed_italic.ttf
          style: italic
          weight: 400
        - asset: fonts/robotocondensed_light.ttf
          style: normal
          weight: 300
        - asset: fonts/robotocondensed_lightitalic.ttf
          style: italic
          weight: 300
        - asset: fonts/robotocondensed_regular.ttf
          style: normal
          weight: 400
    - family: Roboto
      fonts:
        - asset: fonts/roboto_black.ttf
          style: normal
          weight: 900
        - asset: fonts/roboto_blackitalic.ttf
          style: italic
          weight: 900
        - asset: fonts/roboto_bold.ttf
          style: normal
          weight: 700
        - asset: fonts/roboto_bolditalic.ttf
          style: italic
          weight: 700
        - asset: fonts/roboto_light.ttf
          style: normal
          weight: 300
        - asset: fonts/roboto_lightitalic.ttf
          style: italic
          weight: 300
        - asset: fonts/roboto_medium.ttf
          style: normal
          weight: 500
        - asset: fonts/roboto_mediumitalic.ttf
          style: italic
          weight: 500
        - asset: fonts/roboto_regular.ttf
          style: normal
          weight: 400
        - asset: fonts/roboto_thin.ttf
          style: normal
          weight: 100
        - asset: fonts/roboto_thinitalic.ttf
          style: italic
          weight: 100

flutter_intl:
  enabled: true
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated
