name: presenter
description: Flutter presenter module
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  injectable: ^2.1.0
  get_it: ^7.2.0
  messagepack: 0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  injectable_generator:
  build_runner:
  mockito: ^5.3.2
  mocktail: ^0.3.0

flutter:

flutter_intl:
  enabled: true
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated